version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm install -g netlify-cli
      - run: netlify deploy --prod --dir=build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-deploy
